- name: add elasticsearch signing key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: add elasticsearch repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
    update_cache: yes

- name: install elasticsearch 7.4
  apt:
    pkg: elasticsearch
    state: present
  register: installation
  notify:
    - enable elasticsearch service

- name: copy certificates to encrypt internode communication
  copy:
    src: files/elastic-certificates.p12
    dest: /etc/elasticsearch/elastic-certificates.p12

- name: copy elasticsearch config
  template:
    src: elasticsearch.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify:
    - restart elasticsearch

- meta: flush_handlers

- name: set fresh_install fact
  set_fact:
    fresh_install: "{{ installation.changed | default(false) }}"

- name: ensure elasticsearch is started
  service:
    name: elasticsearch
    state: started
