- include_vars:
    file: passwords.yml
    name: passwords

- name: install elasticsearch
  import_tasks: install-elasticsearch.yml

- name: setup users
  import_tasks: users.yml
  when: 
    - elasticsearch.setup_users
    - installation.changed | default(false)
