- name: Add Elasticsearch signing key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
    state: present
    update_cache: yes

- name: Install Elasticsearch
  apt:
    pkg: elasticsearch
    state: present

- name: Ensure Elasticsearch is started
  service:
    name: elasticsearch
    state: started
    enabled: yes