- name: add elasticsearch signing key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: add elasticsearch repository
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
    state: present
    update_cache: yes

- name: install elasticsearch
  apt:
    pkg: elasticsearch
    state: present
  notify:
    - enable elasticsearch service

- name: add elasticsearch config
  template:
    src: elasticsearch.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify:
    - restart elasticsearch

- name: ensure elasticsearch is started
  service:
    name: elasticsearch
    state: started
