- name: remove test database
  mysql_db:
    db: test
    state: absent

- name: create phenopod database
  mysql_db:
    db: phenopod
    state: present

- name: copy schema
  copy:
    src: "files/{{ item }}"
    dest: "/usr/local/schema/{{ item }}"
  loop:
    - 0_1.sql
