- name: install mysql 5.7
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - mysql-server-5.7
    - python3-pymysql
    - mytop

- name: set root user password
  mysql_user:
    name: root
    password: "{{ passwords.root }}"
    host: "{{ item }}"
    priv: "*.*:ALL,GRANT"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - 127.0.0.1
    - ::1
    - localhost

- name: copy user options file
  template:
    src: user.my.cnf.j2
    dest: ~/.my.cnf
    mode: 0600
  notify:
    - restart mysql

- name: copy global options file
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
    mode: 0600
  notify:
    - restart mysql

- name: remove test database
  mysql_db:
    db: test
    state: absent

- name: create phenopod database
  mysql_db:
    db: phenopod
    state: present
