- name: Add Mysql PGP key
  apt_key:
    data: "{{ lookup('file', 'files/signing_key.pem') }}"
    state: present

- name: Add Mysql debian package to APT
  apt_repository:
    repo: deb http://repo.mysql.com/apt/ubuntu/ bionic mysql-8.0
    state: present
    update_cache: yes

- name: Install mysql 
  apt:
    pkg: '{{ packages }}'
    state: present
    update_cache: yes
  vars:
    packages:
    - mysql-server
    - mysql-client
    - mytop