- name: Remove anonymous users
  mysql_user:
    user: ""
    host: "{{ item }}"
    state: absent
  loop:
    - 127.0.0.1
    - ::1
    - localhost

- name: Remove MySQL test database
  mysql_db:
    db: test
    state: absent