- name: create admin user
  mysql_user:
    name: admin
    password: "{{ passwords.admin }}"
    host: "{{ item }}"
    priv: "*.*:ALL,GRANT"
    state: present
  loop:
    - 127.0.0.1
    - ::1
    - localhost

- name: create backup user
  mysql_user:
    name: backup
    password: "{{ passwords.backup }}"
    host: "{{ item }}"
    priv: "*.*:SELECT,LOCK TABLES,RELOAD,PROCESS,TRIGGER,SUPER,REPLICATION CLIENT,SHOW VIEW"
    state: present
  loop:
    - 127.0.0.1
    - ::1
    - localhost

- name: create read_write user
  mysql_user:
    name: read_write
    password: "{{ passwords.read_write }}"
    host: "{{ item }}"
    priv: "*.*:DELETE,INSERT,SELECT,UPDATE"
    state: present
  loop:
    - "%"
    - localhost

- name: remove anonymous users
  mysql_user:
    user: ""
    host: "{{ item }}"
    state: absent
  loop:
    - "%"
    - 127.0.0.1
    - ::1
    - localhost