version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    parallelism: 1

    working_directory: ~/go/src/github.com/varmamsp/

    steps:
      - checkout
      - run:
          name: Hello world
          command: echo "Hello world"
