- name: ensure build directory exists
  file:
    path: "{{ server_build_dir }}"
    state: directory
    mode: 0600

- name: compile server
  command: "/usr/local/go/bin/go build -o {{ server_build_dir }}/server ./cmd/cello/main.go"
  args:
    chdir: "{{ cello_path }}"
  environment:
    GO111MODULE: "on"

- name: load passwords and oauth variables
  include_vars:
    file: "{{ item.file }}"
    name: "{{ item.name }}"
  loop:
    - { file: oauth.yml, name: oauth }
    - { file: passwords.yml, name: passwords }

- name: ensure server configuration exists
  template:
    src: api-server.conf.j2
    dest: "{{ server_build_dir }}/api-server.conf.yml"
