- name: clone repo
  import_tasks: clone-repo.yml

- name: install golang
  import_tasks: install-go.yml

- name: build server
  import_tasks: build.yml

- name: run service
  import_tasks: service.yml
