- name: ensure ui-server service exists
  template:
    src: ui-server.service.j2
    dest: /lib/systemd/system/ui-server.service
  notify:
    - reload systemd

- name: ensure ui-server is started
  service:
    name: ui-server
    state: restarted
    enabled: yes
