- hosts: anton
  tasks:
    - include_role:
        name: elasticsearch
      vars:
        es_reset_user_passwords: true

    - include_role:
        name: kibana

    - include_role:
        name: rabbitmq

    - include_role:
        name: cello

    - include_role:
        name: api-server
      vars:
        redis_host: "{{ hostvars['hal']['private_ip'] }}"
        mysql_host: "{{ hostvars['keyser']['private_ip'] }}"
        minio_host: "{{ hostvars['keyser']['private_ip'] }}"

        import_podcast_enable: true
        import_podcast_worker_limit: 4

        refresh_podcast_enable: true
        refresh_podcast_worker_limit: 20

        create_thumbnail_enable: true
        create_thumbnail_worker_limit: 2

        task_scheduler_enable: true
        task_scheduler_worker_limit: 10

        sync_playback_enable: true
        sync_playback_worker_limit: 1
