- hosts: anton
  tasks:
    - include_role:
        name: elasticsearch
      vars:
        es_reset_user_passwords: true

    - include_role:
        name: kibana

    - include_role:
        name: rabbitmq

    - include_role:
        name: cello

    - include_role:
        name: api-server
      vars:
        redis_host: "{{ hostvars['hal']['private_ip'] }}"
        mysql_host: "{{ hostvars['keyser']['private_ip'] }}"
        minio_host: "{{ hostvars['keyser']['private_ip'] }}"

        task_scheduler_enable: true
        task_scheduler_worker_limit: 10

        sync_playback_enable: true
        sync_playback_worker_limit: 1
