- hosts: hal

  tasks:
    - include_role:
        name: nginx

    - include_role:
        name: redis

    - include_role:
        name: cello

    - include_role:
        name: ui-server

    - include_role:
        name: api-server
      vars:
        mysql_host: "{{ hostvars['keyser']['private_ip'] }}"
        minio_host: "{{ hostvars['keyser']['private_ip'] }}"
        rabbitmq_host: "{{ hostvars['anton']['private_ip'] }}"
        elasticsearch_host: "{{ hostvars['anton']['private_ip'] }}"
