- hosts: keyser
  vars:
    skip_api: false

  tasks:
    - include_role:
        name: mysql

    - include_role:
        name: rabbitmq

    - include_role:
        name: cello

    - include_role:
        name: api-server
      vars:
        elasticsearch_host: "{{ hostvars['anton']['private_ip'] }}"
        redis_host: "{{ hostvars['anton']['private_ip'] }}"

        import_podcast_enable: true
        refresh_podcast_enable: true
        create_thumbnail_enable: false
        scheduler_enable: false
        sync_episode_playback_enable: false

        import_podcast_concurrency: 20
        refresh_podcast_concurrency: 10
      when: skip_api == false
