env: dev

mysql:
  address: localhost:3306
  database: phenopod
  user: root
  password: birds

rabbitmq:
  address: localhost:5672
  user: guest
  password: guest

elasticsearch:
  address: localhost:9200
  user: elastic
  password: changeme

redis:
  address: localhost:6379
  max_idle_conn: 10

minio:
  address: localhost:9000
  access_key_id: H8N6Q04KFKQDA5B9UW5U
  secret_access_key: HgKy1+eDdykb2tfTkulHk9+Fy+Fj9fClF0AN3jOz

queues:
  import_podcast:
    delivery_mode: 2
    consumer_name: import_podcast
    consumer_auto_ack: false
    consumer_exclusive: false
    consumer_prefetch_count: 100

  refresh_podcast:
    delivery_mode: 2
    consumer_name: refresh_podcast
    consumer_auto_ack: false
    consumer_exclusive: false
    consumer_prefetch_count: 100

  create_thumbnail:
    delivery_mode: 2
    consumer_name: create_thumbnail
    consumer_auto_ack: false
    consumer_exclusive: true
    consumer_prefetch_count: 100

  sync_playback:
    delivery_mode: 1
    consumer_name: sync_playback
    consumer_auto_ack: true
    consumer_exclusive: true
    consumer_prefetch_count: 1000

jobs:
  import_podcast:
    enable: true
    worker_limit: 30

  refresh_podcast:
    enable: false
    worker_limit: 50

  create_thumbnail:
    enable: false
    worker_limit: 4

  task_scheduler:
    enable: true
    worker_limit: 10

  sync_playback:
    enable: false

oauth:
  google:
    client_id: 844087729764-4kof4gr262r2u0lhtb5d2a3viqr1p08a.apps.googleusercontent.com
    client_secret: NtmEm0srKHKG-zUMGFccYekR
    redirect_url: http://localhost:8080/api/callback/google
    scopes: ["profile", "email"]

  facebook:
    client_id: 1461695093970060
    client_secret: f302cd975a5ebef96a295486be7b6aa3
    redirect_url: http://localhost:8080/api/callback/facebook
    scopes: ["email"]

  twitter:
    client_id: cmn3dPHdbvuIwh03R1Cy1ajYr
    client_secret: RtzXg4suls5qaJgiH3El2UiKwziXe9KNUGUwEYyPhzYSs8FHNM
    redirect_url: http://localhost:8080/api/callback/twitter
    scopes: []
