env: dev
address: 0.0.0.0:8080

mysql:
  address: mysql:3306
  database: phenopod
  user: root
  password: birds

elasticsearch:
  address: elasticsearch:9200
  user: elastic
  password: birds

rabbitmq:
  address: rabbitmq:5672
  user: guest
  password: birds

redis:
  address: redis:6379
  max_idle_conn: 10

minio:
  address: minio:9000
  access_key: H8N6Q04KFKQDA5B9UW5U
  secret_key: HgKy1+eDdykb2tfTkulHk9+Fy+Fj9fClF0AN3jOz
  region: us-east-1

queues:
  import_podcast:
    delivery_mode: 2
    consumer_name: import_podcast
    consumer_auto_ack: false
    consumer_exclusive: false
    consumer_prefetch_count: 100

  refresh_podcast:
    delivery_mode: 2
    consumer_name: refresh_podcast
    consumer_auto_ack: false
    consumer_exclusive: false
    consumer_prefetch_count: 100

  create_thumbnail:
    delivery_mode: 2
    consumer_name: create_thumbnail
    consumer_auto_ack: false
    consumer_exclusive: true
    consumer_prefetch_count: 100

  sync_playback:
    delivery_mode: 1
    consumer_name: sync_playback
    consumer_auto_ack: true
    consumer_exclusive: true
    consumer_prefetch_count: 1000

jobs:
  import_podcast:
    enable: false
    worker_limit: 30

  refresh_podcast:
    enable: false
    worker_limit: 50

  create_thumbnail:
    enable: false
    worker_limit: 10

  task_scheduler:
    enable: false
    worker_limit: 10

  sync_playback:
    enable: true

oauth:
  google:
    client_id: 844087729764-4kof4gr262r2u0lhtb5d2a3viqr1p08a.apps.googleusercontent.com
    client_secret: NtmEm0srKHKG-zUMGFccYekR
    redirect_url: http://localhost:8080/api/callback/google
    scopes: ["profile", "email"]

  facebook:
    client_id: 1461695093970060
    client_secret: f302cd975a5ebef96a295486be7b6aa3
    redirect_url: http://localhost:8080/api/callback/facebook
    scopes: ["email"]
