- name: enusre minio group exists
  group:
    name: "{{ minio_group }}"
    state: present

- name: ensure minio user exists
  user:
    name: "{{ minio_user }}"
    system: true
    shell: /sbin/login
    group: "{{ minio_group }}"

- name: ensure data and configuration directory exists
  file:
    name: "{{ item }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
  loop:
    - "{{ minio_data_dir }}"
    - "{{ minio_config_dir }}"

- name: ensure minio env file
  template:
    src: env.j2
    dest: /etc/default/minio

- name: download minio and minio client
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: u+x,g+x,o+x
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
  register: installation
  loop:
    - { url: "{{ minio_download_url }}", dest: /usr/local/bin/minio }
    - { url: "{{ minio_client_download_url }}", dest: /usr/local/bin/mc }

- name: set fresh_install fact
  set_fact:
    fresh_install: "{{ installation.changed | default(false) }}"

- name: add host to mc
  command: "/usr/local/bin/mc config host add minio http://{{ hostvars[inventory_hostname]['private_ip'] }}:9000 {{ passwords.access_key }} {{ passwords.secret_key }} --api S3v4"
  when: fresh_install
