- name: enusre minio group exists
  group:
    name: "{{ minio_group }}"
    state: present

- name: ensure minio user exists
  user:
    name: "{{ minio_user }}"
    system: true
    shell: /sbin/login
    group: "{{ minio_group }}"

- name: ensure data and configuration directory exists
  file:
    name: "{{ item }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
  loop:
    - "{{ minio_data_dir }}"
    - "{{ minio_config_dir }}"

- name: ensure minio env file
  template:
    src: env.j2
    dest: /etc/default/minio

- name: download minio
  get_url:
    url: "{{ minio_download_url }}"
    dest: /usr/local/bin/minio
    mode: u+x,g+x,o+x
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
