- name: ensure minio service exists
  template:
    src: minio.service.j2
    dest: /lib/systemd/system/minio.service
  notify:
    - reload systemd

- meta: flush_handlers

- name: restart minio
  service:
    name: minio
    state: restarted
    enabled: yes
