- name: Add Redis PPA
  apt_repository: 
    repo: ppa:chris-lea/redis-server
    state: present
    update_cache: yes 

- name: Install Redis
  apt:
    pkg: redis-server
    state: latest
    update_cache: yes

- name: Start redis as systemd service
  service:
    name: redis-server
    state: started
    enabled: yes
