- name: add redis repository
  apt_repository: 
    repo: ppa:chris-lea/redis-server
    state: present
    update_cache: yes 

- name: install redis-server
  apt:
    pkg: redis-server
    state: latest
    update_cache: yes

- name: edit redis configuration
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  notify:
    - restart redis-server
  loop:
    - { regexp: "^bind.*", line: "bind 127.0.0.1 ::1 {{ hostvars[inventory_hostname]['private_ip'] }}" }
    - { regexp: "^protected-mode.*", line: "protected-mode no" }

- name: ensure redis-server is started
  service:
    name: redis-server
    state: started
    enabled: yes
