- include_vars:
    file: passwords.yml
    name: passwords

# https://www.rabbitmq.com/install-debian.html
- name: install rabbitmq and its dependencies
  import_tasks: install.yml

- name: setup users
  import_tasks: users.yml
