- name: Add Rabbitmq PGP key
  apt_key:
    url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
    state: present

- name: Add Erlang Debian package to APT
  apt_repository: 
    repo: 'deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang-22.x'
    state: present
    update_cache: yes

- name: Add Rabbitmq Debian package to APT
  apt_repository:
    repo: 'deb https://dl.bintray.com/rabbitmq/debian bionic main'
    state: present
    update_cache: yes

- name: Install Erlang packages
  apt:
    pkg: '{{ packages }}'
  vars:
    packages:
    - erlang-base
    - erlang-asn1
    - erlang-crypto
    - erlang-eldap
    - erlang-ftp
    - erlang-inets
    - erlang-mnesia
    - erlang-os-mon
    - erlang-parsetools
    - erlang-public-key
    - erlang-runtime-tools
    - erlang-snmp
    - erlang-ssl
    - erlang-syntax-tools
    - erlang-tftp
    - erlang-tools
    - erlang-xmerl

- name: Install Rabbitmq
  apt:
    pkg: rabbitmq-server
    state: present
    update_cache: yes

- name: Start Rabbitmq as Systemd serice
  service:
    name: rabbitmq-server
    state: started
    enabled: yes

    

