- name: Add Rabbitmq signing key
  apt_key:
    url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
    state: present

- name: Copy erlang prefrences file
  copy:
    src: files/preferences
    dest: /etc/apt/preferences.d/erlang

- name: Add Erlang and Rabbitmq repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang-22.x
    - deb https://dl.bintray.com/rabbitmq/debian bionic main

- name: Install Erlang and Rabbitmq
  apt:
    pkg: '{{ item }}'
    state: present
    update_cache: yes
  loop:
    - erlang-base
    - erlang-asn1
    - erlang-crypto
    - erlang-eldap
    - erlang-ftp
    - erlang-inets
    - erlang-mnesia
    - erlang-os-mon
    - erlang-parsetools
    - erlang-public-key
    - erlang-runtime-tools
    - erlang-snmp
    - erlang-ssl
    - erlang-syntax-tools
    - erlang-tftp
    - erlang-tools
    - erlang-xmerl
    - rabbitmq-server

- name: Ensure rabbitmq server is started
  service:
    name: rabbitmq-server
    state: started
    enabled: yes

    

