- name: delete default guest user
  rabbitmq_user:
    user: guest
    state: absent

- name: create admin user
  rabbitmq_user:
    user: admin
    password: "{{ passwords.admin }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- name: create read_write user
  rabbitmq_user:
    user: read_write
    password: "{{ passwords.read_write }}"
    vhost: /
    configure_priv: ^$
    read_priv: .*
    write_priv: .*
    state: present

- name: create management_admin user
  rabbitmq_user:
    user: management_admin
    password: "{{ passwords.management_admin }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    tags: administrator
    state: present
